[project]
name = "kiwoom-mcp"
version = "0.1.0"
description = "MCP Server for Kiwoom Securities API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.0.0",
    "requests>=2.32.4",
]
